### ISSUE TITLE
Is it possible to add a keyboard with a 75% layout

### ISSUE THREAD

**Issue by Meekdai** [Mostafa-Abbasi/KeyboardTester#1]
Such as Keychron K3
https://www.keychron.com/products/keychron-k3-max-qmk-via-wireless-custom-mechanical-keyboard

**Comment by Mostafa-Abbasi** [comment]
Hey there
Yes, it is possible to add the 75% option. Although I didn't originally have this layout in mind when writing the CSS grid, I guess with some modifications it would be okay.
I'm going to get it done as soon as possible.

**Comment by Mostafa-Abbasi** [comment]
It was done a long time ago, but I forgot to inform. 
Thanks for your feedback, anyway!
