### ISSUE TITLE
Add a right microsoft button

### ISSUE THREAD

**Issue by shoulders** [Mostafa-Abbasi/KeyboardTester#2]
![IMG20240407080629](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/02b832e5-2e78-45c1-97a8-8ec359d4d423)

The left and right Microsoft buttons are different.

Can you add a right button.

thanks

NB: you might be able to get the key code from here if you do not have a keybaord with 2 buttons. https://usevia.app/test (GitHub link at top roght)

**Comment by Mostafa-Abbasi** [comment]
Hi, Sorry for the late reply. 
Adding another windows button here would break the standard keyboard layout, so I guess It's not possible.

**Comment by Mostafa-Abbasi** [comment]
According to this issue, I will replace the windows button with FN key.  
https://github.com/Mostafa-Abbasi/KeyboardTester/issues/3
