### ISSUE TITLE
Function button is always on the left

### ISSUE THREAD

**Issue by shoulders** [Mostafa-Abbasi/KeyboardTester#3]
If you can detect a function button this button is always on the left for laptops and desktops.

![IMG20240407080629](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/02b832e5-2e78-45c1-97a8-8ec359d4d423)

Can you move the button to the left or remove it if it does nothing. I think this button is effectively invisible to the OS.

Thanks

**Comment by Mostafa-Abbasi** [comment]
Hi, that's right, it's invisible to the browser API. I will remove it and replace it with the right Windows key, as you suggested in https://github.com/Mostafa-Abbasi/KeyboardTester/issues/2 .
