### ISSUE TITLE
The right `Alt` should be `Alt Gr` and should be an independent Key

### ISSUE THREAD

**Issue by shoulders** [Mostafa-Abbasi/KeyboardTester#4]
![image](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/f2c6e679-4b72-4f09-839a-029ea426be7f)

![IMG20240407080629](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/02b832e5-2e78-45c1-97a8-8ec359d4d423)

- The right `Alt` should be `Alt Gr`
- IBM named this key "alternate graphic" and it's not a substitute for CTRL + ALT, though CTRL + ALT was implemented as a substitute for ALT GR in Windows. It is a key modifier (like CTRL or SHIFT) that enables a different input than is normally expected of a key.
   - https://superuser.com/questions/220071/whats-the-function-of-the-alt-gr-key

### Proposed solution
- Rename the right `Alt` key to `Alt Gr`
- Detect the `Alt Gr` as an independent Key

**Comment by Mostafa-Abbasi** [comment]
I'm thinking that I should keep the Alt (as right Alt) and not change its legend to Alt Gr, because that is not familiar to most users. 
but also check for Alt Gr code when it is pressed for the sake of completeness, unfortunately I couldn't find the code for Alt Gr key, if you know its exact code, I can implement this feature. 
Reference: https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values

**Comment by shoulders** [comment]
Alt right is wrong because you don't call the left one alt left. Definitely use Alt Gr.

People might know the key as the alt right because it is an alt key on the right hand side.

The enter and return keys are different keys but normal people assume they are the same.

It is best to keep the property names as this is what leads to people using their simple names.

I will see if I can find the keycode for you

Thanks

**Comment by shoulders** [comment]
looks like there is no longer a specific code for AltGr so people emulate it

- https://stackoverflow.com/questions/10657346/detect-alt-gr-alt-graph-modifier-on-key-press
- https://dprincekumar.github.io/keyboard-checking/
- https://joltfly.com/keyboard-test/

```javascript
if (event.ctrlKey && event.altKey) {
    // Appears to be Alt Gr
}
```

**Comment by Mostafa-Abbasi** [comment]
Alright, I added the code to detect the AltGr key press, now if you press it, Right Alt should be highlighted. (which is in the same physical location).
Test it and tell me if it is working as expected.

**Comment by shoulders** [comment]
2 things

- Do not highlight the left `Ctrl` button.
  - The event is checking for both `Ctrl+Alt` to emulate the Right alt/Alt GR button.
  - What happens behind the scenes should stay there.
  - I have manually tried pressing `Ctrl+Alt` to see if it would trigger AltGr detection on those other keyboards and i come to the conclusion, i cannot, the timing must be exact and I am human.
- `Alt Gr` should be the name 😄 of the button, but I can live with `Alt`.

**Comment by Mostafa-Abbasi** [comment]
Alright! I think I finally fixed it! It should now correctly detect the AltGr with the help of e.key.
Test and see how it goes! 😄
Thanks for the feedbacks btw.

**Comment by shoulders** [comment]
- works as expected in chrome
- Works as expected in Firefox, but the `left ctrl` flickers when you press `AltGr , however it does not stay illuminated.

Your welcome, thanks for the keyboard tester.

**Comment by Mostafa-Abbasi** [comment]
Glad to hear that it works. 
That flickering issue must be the delay of the browser to execute this part of the code:

```
document.querySelector('.' + 'controlleft').classList.remove('key-pressing-simulation');
document.querySelector('.' + 'controlleft').classList.remove('key--pressed');
```

I think the current implementation is good enough, if I figured out a better solution, I will replace it.
