### ISSUE TITLE
rename the main `Enter` key to `Return`

### ISSUE THREAD

**Issue by shoulders** [Mostafa-Abbasi/KeyboardTester#5]
A keyboard does not have 2 enter keys although some manufacturers got lazy and did not understand they were different.

The `enter` key on the main section is actually the `Return` key (carriage return, hence the arrow you sometimes see, a through back to type-writers)

https://en.wikipedia.org/wiki/Enter_key

**UK Keyboard**
![image](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/b25f84dc-0064-4b9d-a651-74daab74e0f4)

**US Keyboard**
![image](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/cdfca9c5-da04-4cd5-8f10-af524497a7ed)

### Proposed solution

Rename the main `Enter` key to `Return`

![image](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/6684fb66-88f8-438a-81b1-3b3ed3929dfb)

**Comment by Mostafa-Abbasi** [comment]
That's a good point.  I renamed the key from "Enter" to "return sign".
Thanks.

**Comment by shoulders** [comment]
its the small things in life 😄 

Thanks

**Comment by shoulders** [comment]
![image](https://github.com/user-attachments/assets/c07fcee3-1c7a-482a-8aff-a411fa3c2c10)

any chance you can put a tail on it, looks like a delete/backspace key

![image](https://github.com/user-attachments/assets/a3ecd33b-920d-43ee-be54-6208a3b50434)
