### ISSUE TITLE
Add UK layout

### ISSUE THREAD

**Issue by shoulders** [Mostafa-Abbasi/KeyboardTester#7]
This would be a nice feature to have but not essential. I have always preffered the UK layout and I think it might have one more key to accommodate the £ symbol.

https://en.wikipedia.org/wiki/Enter_key

![1920px-ISO_British_QWERTY_(Windows)_Enter_Return svg](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/bf2b06f7-617f-46f5-a403-ecee4ec5016b)

My Keyboard

![image](https://github.com/Mostafa-Abbasi/KeyboardTester/assets/319997/be83de08-d1fe-44b2-bce6-6e87b4e30b8f)

- the print screen, scroll lock and pause button are not in the standard place
- ignore the search button
- ignore the calculator button. This is part of the extended media buttons but not all keyboards have this and there is no standard layout
- the `Fn` button is not on all keyboards and I think it is not a proper key.

**Comment by Mostafa-Abbasi** [comment]
Most keyboards that I saw online are using ANSI United States layout by default, so I think it's not really necessary to add other layouts as well. 
IMO, implementing multiple layouts would introduce spaghetti code, which is not suitable for future maintenance. 
Thanks for your input, anyway.

**Comment by shoulders** [comment]
Fair enough. If you don't ask you don't get 😄 

I don't know how people manage with the ANSI United States layout, I tried one once it did not go well. :)
